GRANT ALL PRIVILEGES ON *.* TO 'chanakan'@'%';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS old_users (
  id INT NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

create table if not exists users (
    student_id BIGINT not null PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
    Fname VARCHAR(255) DEFAULT NULL,
    Lname VARCHAR(255) DEFAULT NULL,
    faculty VARCHAR(255) DEFAULT NULL,
    dept VARCHAR(255) DEFAULT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) DEFAULT NULL,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP()
);